server:
  port: 8001
spring:
  application:
    name: AIGOU-ZUUL
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
zuul:
  routes:
    aigou_plat: /login/**
  ignored-services: "*"
  prefix: /aigou
